# .github/workflows/deploy.yml
name: Deploy (production)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # allow pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint / Types / Tests
        run: |
          npm run lint
          npm run type-check
          npm test

      - name: Set git identity (for gh-pages commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy (gh-pages)
        run: npm run deploy
